// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2rI0woDqwD3f9NnMyERKFW1nMDRST6Rc',
    appId: '1:313226788999:web:70749722fc6b53e853f822',
    messagingSenderId: '313226788999',
    projectId: 'cabskaro-2fc88',
    authDomain: 'cabskaro-2fc88.firebaseapp.com',
    storageBucket: 'cabskaro-2fc88.appspot.com',
    measurementId: 'G-KZC15HZTT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9hj-AeVscH1FVftdXYH74rPSdXGaeMOE',
    appId: '1:313226788999:android:74b1fe08f7a0549453f822',
    messagingSenderId: '313226788999',
    projectId: 'cabskaro-2fc88',
    storageBucket: 'cabskaro-2fc88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQCQzHyGtYWiCRxu0kUhK9INbIFIVEGVI',
    appId: '1:313226788999:ios:a4122d471873f27d53f822',
    messagingSenderId: '313226788999',
    projectId: 'cabskaro-2fc88',
    storageBucket: 'cabskaro-2fc88.appspot.com',
    iosBundleId: 'com.example.cabskaro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQCQzHyGtYWiCRxu0kUhK9INbIFIVEGVI',
    appId: '1:313226788999:ios:c7dce98ff3be544a53f822',
    messagingSenderId: '313226788999',
    projectId: 'cabskaro-2fc88',
    storageBucket: 'cabskaro-2fc88.appspot.com',
    iosBundleId: 'com.example.cabskaro.RunnerTests',
  );
}
