// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFaa89ihoIY2y9WRk04_-R-X1YNl6suyk',
    appId: '1:980632885970:web:77123f605b6ef29ac5eb0b',
    messagingSenderId: '980632885970',
    projectId: 'cabskaro-a66d8',
    authDomain: 'cabskaro-a66d8.firebaseapp.com',
    storageBucket: 'cabskaro-a66d8.appspot.com',
    measurementId: 'G-TPWLCCD4TY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHLJCkp1X-48jeTUWwKMJsebEkmJG9zS4',
    appId: '1:980632885970:android:44c7e1a775fc8852c5eb0b',
    messagingSenderId: '980632885970',
    projectId: 'cabskaro-a66d8',
    storageBucket: 'cabskaro-a66d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-BlSp8izBF2GMpheX5ax-E3OmdcYLVQM',
    appId: '1:980632885970:ios:2824d0e92385b8e7c5eb0b',
    messagingSenderId: '980632885970',
    projectId: 'cabskaro-a66d8',
    storageBucket: 'cabskaro-a66d8.appspot.com',
    iosBundleId: 'com.example.cabskaro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-BlSp8izBF2GMpheX5ax-E3OmdcYLVQM',
    appId: '1:980632885970:ios:b720ab540e86f351c5eb0b',
    messagingSenderId: '980632885970',
    projectId: 'cabskaro-a66d8',
    storageBucket: 'cabskaro-a66d8.appspot.com',
    iosBundleId: 'com.example.cabskaro.RunnerTests',
  );
}
